### ISSUE TITLE
TypeError: collection is undefined

### ISSUE THREAD

**Issue by avishshah11** [godnondsilva/crwn-clothing-project#2]
Hey @godnondsilva , I am trying to make same project but I am get error in src/pages/collection/collection.component.jsx; 
and error is `collection is undefined`. Can you please help me out ?

**Comment by godnondsilva** [comment]
Hey, thanks for contacting me. The best thing you can do is check my
GitHub, copy parts of the code from my repo and paste it in your file, see
if that helps. If it does, compare my code with yours, you will find out
what's wrong. (You can also use yihua's code)

**Comment by godnondsilva** [comment]
Hey, The best thing you can do is check my
GitHub, copy parts of the code from my repo and paste it in your file, see
if that helps. If it does, compare my code with yours, you will find out
what's wrong. (You can also use yihua's code)

If you still are having doubts, you can contact me on discord: Gxd#3055

**Comment by avishshah11** [comment]
Thank you! I will see to it

**Comment by avishshah11** [comment]
@godnondsilva Error solved. Thanks for helping me out

**Comment by godnondsilva** [comment]
Happy to help! 😄
